[server]
# Port for snapclient
port = 1704

[http]
# Port for snapweb/websocket
enabled = true
bind_to_address = 0.0.0.0
port = 1780

[stream]
# Source from the librespot named pipe
# Updated to 44.1kHz stereo to match librespot's default output
source = pipe://../fifo/snapfifo?name=spatial&sampleformat=44100:16:2&codec=flac
